# Generated by Django 2.0 on 2017-12-12 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_tasklist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Date Completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created'),
        ),
    ]
