# Generated by Django 2.0 on 2018-03-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(blank=True, null=True)),
                ('docid', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('is_known', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_key', models.CharField(max_length=20, unique=True)),
                ('is_real', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(to='fc_stats.Product'),
        ),
    ]
